# Generated by Django 5.1.1 on 2024-09-08 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='registered'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('CEO', 'CEO'), ('CTO', 'CTO'), ('DEVELOPER', 'Developer'), ('DESIGNER', 'Designer'), ('PRODUCT_OWNER', 'Product Owner'), ('PROJECT_OWNER', 'Project Owner'), ('PROGRAMMER', 'Programmer'), ('PROJECT_MANAGER', 'Project Manager'), ('QA', 'QA')], default='PROGRAMMER', max_length=30),
        ),
    ]
