# Generated by Django 5.1.1 on 2024-09-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('PENDING', 'PENDING'), ('BLOCKED', 'BLOCKED'), ('TESTING', 'TESTING'), ('CLOSED', 'CLOSED')], default='NEW', max_length=15),
        ),
    ]
